import { describe, expect, it, vi, beforeEach } from "vitest";
import { appRouter } from "./routers";
import type { TrpcContext } from "./_core/context";

// vi.mock must use inline functions (no external references)
vi.mock("./db", () => {
  const addShoppingItem = vi.fn().mockImplementation(async (data: any) => ({
    id: Math.floor(Math.random() * 1000),
    ...data,
    isChecked: false,
    createdAt: new Date(),
  }));
  const clearAutoGeneratedShoppingItems = vi.fn().mockResolvedValue(undefined);
  const getInventory = vi.fn().mockResolvedValue([]);

  return {
    getAllUsers: vi.fn().mockResolvedValue([]),
    getUserById: vi.fn().mockResolvedValue(null),
    createUser: vi.fn().mockResolvedValue({ id: 1, name: "Тест", pin: "hash", role: "user" }),
    updateUserPin: vi.fn().mockResolvedValue(undefined),
    getRecipes: vi.fn().mockResolvedValue([]),
    getRecipeById: vi.fn().mockImplementation(async (id: number) => {
      if (id === 1) return {
        id: 1, title: "Омлет", servings: 2, imageUrl: null,
        ingredients: [
          { id: 1, recipeId: 1, name: "Яйца", amount: 3, unit: "шт", orderIndex: 0 },
          { id: 2, recipeId: 1, name: "Молоко", amount: 100, unit: "мл", orderIndex: 1 },
          { id: 3, recipeId: 1, name: "Соль", amount: null, unit: "", orderIndex: 2 },
        ],
        steps: [],
      };
      if (id === 2) return {
        id: 2, title: "Блины", servings: 4, imageUrl: null,
        ingredients: [
          { id: 4, recipeId: 2, name: "Яйца", amount: 2, unit: "шт", orderIndex: 0 },
          { id: 5, recipeId: 2, name: "Молоко", amount: 500, unit: "мл", orderIndex: 1 },
          { id: 6, recipeId: 2, name: "Мука", amount: 300, unit: "г", orderIndex: 2 },
          { id: 7, recipeId: 2, name: "Сахар", amount: 50, unit: "г", orderIndex: 3 },
        ],
        steps: [],
      };
      return null;
    }),
    createRecipe: vi.fn().mockResolvedValue({ id: 1, title: "Тест" }),
    getShoppingList: vi.fn().mockResolvedValue([]),
    addShoppingItem,
    toggleShoppingItem: vi.fn().mockResolvedValue(undefined),
    clearCheckedItems: vi.fn().mockResolvedValue(undefined),
    deleteShoppingItem: vi.fn().mockResolvedValue(undefined),
    clearAutoGeneratedShoppingItems,
    getDashboardStats: vi.fn().mockResolvedValue({ recipeCount: 0, shoppingCount: 0, inventoryCount: 0 }),
    getInventory,
    getProducts: vi.fn().mockResolvedValue([]),
    getOrCreateWeeklyMenu: vi.fn().mockResolvedValue({
      id: 10,
      weekStart: "2025-01-06",
      userId: 1,
      items: [
        { id: 1, menuId: 10, recipeId: 1, dayOfWeek: 0, mealType: "breakfast", servings: 2 },
        { id: 2, menuId: 10, recipeId: 2, dayOfWeek: 0, mealType: "lunch", servings: 4 },
      ],
    }),
    addMenuItem: vi.fn().mockResolvedValue({ id: 1 }),
    removeMenuItem: vi.fn().mockResolvedValue(undefined),
  };
});

// Import the mocked module to access mock functions
import * as db from "./db";

function makeCtx(): TrpcContext {
  return {
    user: null,
    req: { protocol: "https", headers: {} } as TrpcContext["req"],
    res: {
      cookie: vi.fn(),
      clearCookie: vi.fn(),
    } as unknown as TrpcContext["res"],
  };
}

const caller = appRouter.createCaller(makeCtx());

describe("generateShoppingList — ingredient merging", () => {
  beforeEach(() => {
    vi.clearAllMocks();
    // Reset inventory to empty for basic merging tests
    (db.getInventory as any).mockResolvedValue([]);
  });

  it("merges same ingredients from multiple recipes (яйца: 3 + 2 = 5)", async () => {
    const result = await caller.menu.generateShoppingList({ weekStart: "2025-01-06", userId: 1 });
    expect(result.success).toBe(true);

    const eggCall = (db.addShoppingItem as any).mock.calls.find(
      (call: any[]) => call[0].name.toLowerCase() === "яйца"
    );
    expect(eggCall).toBeDefined();
    expect(eggCall![0].amount).toBe(5); // 3 from Омлет + 2 from Блины
    expect(eggCall![0].unit).toBe("шт");
  });

  it("merges same ingredients with same unit (молоко: 100 + 500 = 600 мл)", async () => {
    const result = await caller.menu.generateShoppingList({ weekStart: "2025-01-06", userId: 1 });
    expect(result.success).toBe(true);

    const milkCall = (db.addShoppingItem as any).mock.calls.find(
      (call: any[]) => call[0].name.toLowerCase() === "молоко"
    );
    expect(milkCall).toBeDefined();
    expect(milkCall![0].amount).toBe(600); // 100 + 500
    expect(milkCall![0].unit).toBe("мл");
  });

  it("adds items without numeric amount (like Соль) with undefined amount", async () => {
    await caller.menu.generateShoppingList({ weekStart: "2025-01-06", userId: 1 });

    const saltCall = (db.addShoppingItem as any).mock.calls.find(
      (call: any[]) => call[0].name.toLowerCase() === "соль"
    );
    expect(saltCall).toBeDefined();
    expect(saltCall![0].amount).toBeUndefined();
  });

  it("assigns correct categories to ingredients", async () => {
    await caller.menu.generateShoppingList({ weekStart: "2025-01-06", userId: 1 });

    const eggCall = (db.addShoppingItem as any).mock.calls.find(
      (call: any[]) => call[0].name.toLowerCase() === "яйца"
    );
    expect(eggCall![0].category).toBe("Бакалея");

    const milkCall = (db.addShoppingItem as any).mock.calls.find(
      (call: any[]) => call[0].name.toLowerCase() === "молоко"
    );
    expect(milkCall![0].category).toBe("Молочные");

    const flourCall = (db.addShoppingItem as any).mock.calls.find(
      (call: any[]) => call[0].name.toLowerCase() === "мука"
    );
    expect(flourCall![0].category).toBe("Бакалея");
  });
});

describe("generateShoppingList — idempotency", () => {
  beforeEach(() => {
    vi.clearAllMocks();
    (db.getInventory as any).mockResolvedValue([]);
  });

  it("calls clearAutoGeneratedShoppingItems with userId and menuId before adding", async () => {
    await caller.menu.generateShoppingList({ weekStart: "2025-01-06", userId: 1 });

    expect(db.clearAutoGeneratedShoppingItems).toHaveBeenCalledWith(1, 10);
    expect(db.clearAutoGeneratedShoppingItems).toHaveBeenCalledTimes(1);
  });

  it("repeated calls clear and regenerate (no duplicates)", async () => {
    await caller.menu.generateShoppingList({ weekStart: "2025-01-06", userId: 1 });
    await caller.menu.generateShoppingList({ weekStart: "2025-01-06", userId: 1 });

    expect(db.clearAutoGeneratedShoppingItems).toHaveBeenCalledTimes(2);
  });

  it("stores menuId on each generated shopping item", async () => {
    await caller.menu.generateShoppingList({ weekStart: "2025-01-06", userId: 1 });

    for (const call of (db.addShoppingItem as any).mock.calls) {
      expect(call[0].menuId).toBe(10);
    }
  });
});

describe("generateShoppingList — inventory subtraction", () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it("subtracts inventory from needed amounts (молоко: need 600, have 200 → buy 400)", async () => {
    (db.getInventory as any).mockResolvedValue([
      { id: 1, userId: 1, name: "Молоко", amount: 200, unit: "мл", location: "fridge" },
      { id: 2, userId: 1, name: "Яйца", amount: 2, unit: "шт", location: "fridge" },
    ]);

    const result = await caller.menu.generateShoppingList({ weekStart: "2025-01-06", userId: 1 });
    expect(result.success).toBe(true);

    const milkCall = (db.addShoppingItem as any).mock.calls.find(
      (call: any[]) => call[0].name.toLowerCase() === "молоко"
    );
    expect(milkCall).toBeDefined();
    expect(milkCall![0].amount).toBe(400); // 600 - 200
  });

  it("subtracts inventory from eggs (need 5, have 2 → buy 3)", async () => {
    (db.getInventory as any).mockResolvedValue([
      { id: 1, userId: 1, name: "Яйца", amount: 2, unit: "шт", location: "fridge" },
    ]);

    await caller.menu.generateShoppingList({ weekStart: "2025-01-06", userId: 1 });

    const eggCall = (db.addShoppingItem as any).mock.calls.find(
      (call: any[]) => call[0].name.toLowerCase() === "яйца"
    );
    expect(eggCall).toBeDefined();
    expect(eggCall![0].amount).toBe(3); // 5 - 2
  });

  it("adds inventory context note when partially covered", async () => {
    (db.getInventory as any).mockResolvedValue([
      { id: 1, userId: 1, name: "Молоко", amount: 200, unit: "мл", location: "fridge" },
    ]);

    await caller.menu.generateShoppingList({ weekStart: "2025-01-06", userId: 1 });

    const milkCall = (db.addShoppingItem as any).mock.calls.find(
      (call: any[]) => call[0].name.toLowerCase() === "молоко"
    );
    expect(milkCall![0].note).toContain("в запасах: 200 мл");
    expect(milkCall![0].note).toContain("нужно купить: 400 мл");
  });

  it("skips items fully covered by inventory and reports skipped count", async () => {
    (db.getInventory as any).mockResolvedValue([
      { id: 1, userId: 1, name: "Мука", amount: 500, unit: "г", location: "pantry" },
    ]);

    const result = await caller.menu.generateShoppingList({ weekStart: "2025-01-06", userId: 1 });
    expect(result.skipped).toBe(1);

    const flourCall = (db.addShoppingItem as any).mock.calls.find(
      (call: any[]) => call[0].name.toLowerCase() === "мука"
    );
    expect(flourCall).toBeUndefined();
  });

  it("does not add note when no inventory overlap", async () => {
    (db.getInventory as any).mockResolvedValue([]);

    await caller.menu.generateShoppingList({ weekStart: "2025-01-06", userId: 1 });

    for (const call of (db.addShoppingItem as any).mock.calls) {
      expect(call[0].note).toBeUndefined();
    }
  });
});
